version: '3' 
services:
    redis-server:
        image: "redis"
        volumes:
            - ./redis:/data
    node-app:
        build: .
        image: "poorvajaraypudi/visits"
        ports:
            - "8081:8081"
