version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./server
    image: "poorvajaraypudi/complex-api"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  #client server
  client:
    build:
      context: ./client
    image: "poorvajaraypudi/complex-client"

  #worker service
  worker:
    build:
      context: ./worker
    image: "poorvajaraypudi/complex-worker"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
