#Specify Base Image
FROM node:16-alpine
 
# Work Directory
WORKDIR /usr/app

# Copy package.json into the container
COPY package.json .
 
# Install Dependencies
RUN npm install

# Copy the rest of the files in to the Container
COPY  . .
 
# Run this
CMD ["npm", "run", "serve"]